routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('costumer/reserve');
});
Route::get('/generate-code', 'GenerateController@display');
//order stage
Route::post('/order', 'TransactionController@stageone');
Route::post('/reorder', 'TransactionController@reorder')->name('reorder');
Route::post('/preparing', 'TransactionController@stagetwo');
Route::post('/request', 'RequestController@store');
Route::get('/done/{id}', 'TransactionController@stagethree')->name('done');
Route::get('/prep/{id}', 'TransactionController@prep')->name('prep');
Route::get('/qrto/{userid}/{pass}/{test}', 'TransactionController@qrRetrive')->name('qr');
Route::get('/testdb', 'TransactionController@test')->name('test');

//admin
Route::post('/status-change', 'AdminController@changeStatus');
Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');
Route::get('/void-order/{id}', 'TransactionController@void')->name('void');
Route::resource('table', 'TableController');
Route::resource('food', 'MenuController');
Route::resource('category', 'CategoryController');
Route::get('reports', 'ReportsController@index')->name('report');
Route::get('reports/{cat}/{date}', 'ReportsController@reportDate')->name('reports');
Route::get('export/{start}/{end}', 'ReportsController@export')->name('export');
Route::get('sale-export/{start}/{end}', 'ReportsController@salesExport')->name('sales-export');
Route::get('sales', 'ReportsController@sales')->name('sales');
Route::get('sales/{start}/{end}', 'ReportsController@salesDate');
Route::post('category/destroy', 'CategoryController@destroy')->name('category.remove');
Route::post('table/destroy', 'TableController@destroy')->name('table.remove');
Route::post('food/destroy', 'MenuController@destroy')->name('food.remove');
Route::post('request/destroy', 'RequestController@destroy')->name('request.remove');
Route::post('food/feat', 'MenuController@feat')->name('food.feat');
Route::post('food/active', 'MenuController@active')->name('food.availability');

resources/views/admin/category.blade.php
@extends('layouts.app')

@section('content')
@include('admin/form-category')
<table  class="table table-striped table-bordered">
	<tr>
		<th>ID</th>
		<th>Category</th>
		<th>Delete</th>
	</tr>
	@foreach ($tables as $table)
	<tr>
		<td>{{$table->id}}</td>
		<td>{{$table->name}}</td>
		<td>
			<form action="{{route('category.remove')}}" method="POST">
				@csrf
				<input type="hidden" name="id" value="{{$table->id}}">
				<button class="btn btn-secondary delete" type="submit">Delete</button></td>
			</form>

		</td>
	</tr>
	@endforeach
</table>


@endsection

@section('script')

@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('style')
#request .col-3{
padding:0;
}
.done{
background-color:mistyrose;
}
.new{
background-color:orange;
}
.ordered{
background-color:yellow;
}
.served{
background-color:lightgreen;
}
.paid{
background-color:lightblue;
}
.manual{
background-color:violet;
}
form center{
    display:flex;
}
form center *{
    flex:auto;
}
h2{
    display:flex;
}
span.right{
    margin-left:auto;
}
@endsection
@section('content')

<div class="row " id='request'>

</div>
<!-- Modal -->
<div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="orderModalLabel">Order: <span id="orderModalUsername"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<table border="0">
            <tr>
                <th>Menu</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
            <tbody id="orderModalOrders">

            </tbody>
	      	<tr>
	      		<th>Total:</th>
	      		<td id="orderModalPrice"></td>
	      	</tr>
      	</table>

      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
$(document).ready(function(load) {

    function loadRequest(){
        $.getJSON( "/api/costumers", function(data) {
            $("#request").html('');
            var txt = '';
            $.each(data, function(i, table) {
                table = table.table;
                txt += "<div class='card col-3'>";
                txt += " <div class='card-header'><h2><span>Table:" + table.id +"</span></h2></div>";
                if(table.status == "done" || table.status == "void" || table.status == "vacant"){
                    txt += " <div class='card-body done'>";
                }
                else if(table.status == "reserved" || table.status == "ordering" || table.status == "reordering"){
                    txt += " <div class='card-body new'>";
                }
                else if(table.status == "recording" || table.status == "cooking" || table.status == "preparing"){
                    txt += " <div class='card-body ordered'>";
                }
                else if(table.status == "manual"){
                    txt += " <div class='card-body manual'>";
                }
                else if(table.status == "serving" || table.status == "eating"){
                    txt += " <div class='card-body served'>";
                }
                else if(table.status == "billout" || table.status == "paid"){
                    txt += " <div class='card-body paid'>";
                }
                else{
                    txt += " <div class='card-body'>";
                }
                if(table.transaction ){
                if(table.status == "done" || table.status == "void"  || table.status == "vacant"){}
                else{
                    txt += "<table>"
                    if(table.transaction.order){
                        txt += "<tr><th>Menu</th><th>Quantity</th><th>Price</th><th>Total</th></tr>"
                        $.each(table.transaction.order, function(i, order) {
                            if(order.quantity != 0){
                                txt += "<tr><td>"+order.menu.name+"</td><td>"+order.quantity+"</td><td>"+order.menu.price+"</td><td>"+order.menu.price*order.quantity+"</td></tr>"
                            }
                        });
                    }
                    txt += " </table>";
                }}
                txt += "</div>";
                txt += " <div class='card-footer'>";
                if(table.status == "done" || table.status == "void" || table.status == "vacant"){
                    txt += "<center><h3>Vacant</h3></center>"
                } else {
                if(table.transaction){

                        txt += '<form method="post" action="/status-change"><center>';
                        txt += ' @csrf';
                        txt += ' <input type="hidden" name="id" value="'+table.transaction.id+'">';
                        if(table.status == "recording"){
                            txt += '<a><button type="submit" class="btn btn-primary">Record</button></a>';
                            txt += '<input type="hidden" name="status" value="cooking">';
                        } else if(table.status == "cooking"){
                            txt += '<a><button type="submit" class="btn btn-primary">Prepare</button></a>';
                            txt += '<input type="hidden" name="status" value="preparing">';
                        } else if(table.status == "preparing"){
                            txt += '<a><button type="submit" class="btn btn-primary">Serve</button></a>';
                            txt += '<input type="hidden" name="status" value="served">';
                        } else if(table.status == "served"){
                            txt += '<a><button type="submit" class="btn btn-primary">Served</button></a>';
                            txt += '<input type="hidden" name="status" value="eating">';
                        } else if(table.status == "eating"){
                            txt += '<a><button type="submit" class="btn btn-primary">Bill Out</button></a>';
                            txt += '<input type="hidden" name="status" value="billout">';
                        } else if(table.status == "billout"){
                            txt += '<a><button type="submit" class="btn btn-primary">Paid</button></a>';
                            txt += '<input type="hidden" name="status" value="paid">';
                        } else if(table.status == "paid"){
                            txt += '<a><button type="submit" class="btn btn-primary">Done</button></a>';
                            txt += '<input type="hidden" name="status" value="done">';
                        } else if(table.status == "manual") {
                            txt += '<button type="submit" class="btn btn-primary">Done</button>';
                            txt += '<input type="hidden" name="status" value="done">';
                            txt += '<a href="/qrto/'+table.transaction.username+'/'+table.transaction.pass+'/qrcode"><button type="button" class="btn btn-primary">Order</button></a>';
                        } else {
                            txt += "<h3>Wait</h3>"
                        }
                        txt += "<a href='/void-order/"+table.transaction.id+"'><button type='submit' class='btn btn-primary'>Void</button></a></center></form>";
                    }}

                    txt += "</div></div>";
                });

            $("#request").append(txt);
        });
    }
    loadRequest()
    setInterval(loadRequest, 3000);
});



@endsection
@section('data')
api/costumers @endsection

resources/views/admin/form-category.blade.php
<form method="POST" action="{{route('category.store')}}">
	@csrf
    <div class="form-group row">
        <div class="col-sm-5">
	        <input type="text" name="name" class="form-control" placeholder="Category Name">
	    </div>

        <div class="col-sm-5">
            <input type="submit" class="btn btn-primary" name="submit" value="Add">
        </div>
    </div>
</form>

resources/views/admin/form-menu.blade.php
<form action="{{ route('food.store') }}" method="POST" enctype="multipart/form-data">
	@csrf
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="menu-name">Menu Name</span>
        </div>
        <input type="text" class="form-control" name="name" id="menuname" placeholder="Menu Name" aria-label="Username" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="menu-price">Menu Price</span>
        </div>
        <input type="number" class="form-control" name="price" id="menuprice" placeholder="Menu Price" aria-label="Username" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="menu-prepare">Prepare Time</span>
        </div>
        <input type="number" class="form-control" name="prepare_time" id="menuprepare" placeholder="Menu Prepare Time" aria-label="Username" aria-describedby="basic-addon1">
        <div class="input-group-prepend">
            <span class="input-group-text" id="menu-min">Mins</span>
        </div>
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">Menu Description</span>
        </div>
        <textarea class="form-control" placeholder="Menu Description" name="desc" id="menudesc" aria-label="Menu Description"></textarea>
    </div>
	<div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">Upload</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" name="pic" id="inputGroupFile01">
            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
        </div>
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect01">Category:</label>
        </div>
        <select class="custom-select" name="category_id" id="inputGroupSelect01">
            <option selected>Choose...</option>
            @foreach($cats as $cat)
                <option value="{{$cat->id}}">{{$cat->name}}</option>
            @endforeach
        </select>
    </div>
	<input type="submit" class="btn btn-primary" name="Submit">
</form>

resources/views/admin/form-table.blade.php
    <div class="form-group row">
        <div class="col-sm-1">
            <form method="POST" action="{{route('table.store')}}">
                @csrf
                <input type="hidden" class="form-control" name="place" value="name" placeholder="Table Place">
                <input type="hidden" name="status" value="vacant" >
                <input type="submit" class="btn btn-primary" name="submit" value="Add">
            </form>
        </div>
        <div class="col-sm-1">
            <form action="{{route('table.remove')}}" method="POST">
                @csrf
                <button class="btn btn-secondary delete" type="submit">Delete</button></td>
            </form>
        </div>
    </div>

resources/views/admin/menu-edit.blade.php
@extends('layouts.app')

@section('content')
<form action="{{ route('food.update',['food'=>$menu->id]) }}" method="POST" enctype="multipart/form-data">
    @csrf
    <input name="_method" type="hidden" value="PUT">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="menu-name">Menu Name</span>
        </div>
        <input type="text" class="form-control" name="name" value="{{$menu->name}}" id="menuname" placeholder="Menu Name" aria-label="Username" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="menu-price">Menu Price</span>
        </div>
        <input type="number" class="form-control" name="price" value="{{$menu->price}}" id="menuprice" placeholder="Menu Price" aria-label="Username" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="menu-prepare">Prepare Time</span>
        </div>
        <input type="number" class="form-control" name="prepare_time" value="{{$menu->prepare_time}}" id="menuprepare" placeholder="Menu Prepare Time" aria-label="Username" aria-describedby="basic-addon1">
        <div class="input-group-prepend">
            <span class="input-group-text" id="menu-min">Mins</span>
        </div>
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">Menu Description</span>
        </div>
        <textarea class="form-control" placeholder="Menu Description" name="desc" id="menudesc" aria-label="Menu Description">{{$menu->desc}}</textarea>
    </div>
	<div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">Upload</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" name="pic" id="inputGroupFile01">
            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
        </div>
    </div>
    <img src="{{asset('/img/'.$menu->pic)}}" width="200px">
    <div class="input-group mb-3 mt-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect01">Category:</label>
        </div>
        <select class="custom-select" name="category_id" id="inputGroupSelect01">
            <option value="{{$menu->category->id}}" selected>{{$menu->category->name}}</option>
            @foreach($cats as $cat)
                @if($menu->category->id === $cat->id)
                @else
                <option value="{{$cat->id}}">{{$cat->name}}</option>
                @endif
            @endforeach
        </select>
    </div>
	<input type="submit" class="btn btn-primary" name="Submit">
</form>

@endsection

@section('script')

@endsection

resources/views/admin/menu.blade.php
@extends('layouts.app')

@section('content')
<button class="btn btn-primary" type="button" data-toggle="modal" data-target="#orderModal">
Add Menu
</button>
<table  class="table table-striped table-bordered">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Category</th>
		<th>Preptime</th>
		<th>Feature</th>
		<th>Availability</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	@foreach ($tables as $table)
	<tr>
		<td>{{$table->id}}</td>
		<td>{{$table->name}}</td>
        <td>{{$table->category['name']}}</td>
        <td>{{$table->prepare_time}}</td>
		<td>
			<form id="table-status" method="POST" action="{{route('food.feat')}}">
				@csrf
				<input type="hidden" name="id" value="{{$table->id}}">
				@switch($table->feat)
					@case(0)
						<input type="hidden" name="binary" value="1">
						<a href=""><button type="submit" class="btn btn-primary">Feature</button></a>
					@break
					@case(1)
						<input type="hidden" name="binary" value="0">
						<a href=""><button type="submit" class="btn btn-primary">Remove</button></a>
					@break
				@endswitch
			</form>
		</td>
		<td>
			<form id="table-status" method="POST" action="{{route('food.availability')}}">
				@csrf
				<input type="hidden" name="id" value="{{$table->id}}">
				@switch($table->active)
					@case(0)
						<input type="hidden" name="binary" value="1">
						<a href=""><button type="submit" class="btn btn-primary">Available</button></a>
					@break
					@case(1)
						<input type="hidden" name="binary" value="0">
						<a href=""><button type="submit" class="btn btn-primary">Unavailable</button></a>
					@break
				@endswitch
			</form>
		</td>
		<td>
			<a href="{{route('food.edit',['food'=>$table->id])}}"><button class="btn btn-secondary edit">Edit</button></a>
		</td>
		<td>
			<form action="{{route('food.remove')}}" method="POST">
				@csrf
				<input type="hidden" name="id" value="{{$table->id}}">
				<button class="btn btn-secondary delete" type="submit">Delete</button>
			</form>
		</td>
	</tr>
	@endforeach
</table>

    <!-- Modal -->
<div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="orderModalLabel">Add Menu <span id="orderModalUsername"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            @include('admin/form-menu')
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')

@endsection

resources/views/admin/reports.blade.php
@extends('layouts.app')
@section('style')
td, th{
    text-align:center!important;
    padding:10px;
}
td.right{
    display:flex;
}
@endsection
@section('content')
<div class="filter" style="margin-bottom:20px">
        <label>DATE</label>
        <input type="date" name="start_date" id="start_date" value="{{$start_date}}">
        <input type="date" name="end_date" id="end_date" value="{{$end_date}}">
        <a><button class="btn btn-primary" id="search">Search</button></a>
        <a href="{{route('export', ['start'=>$start_date,'end'=>$end_date])}}"><button class="btn btn-primary" >Export</button></a>
</div>
<table id="table" class="table table-striped table-bordered">
	<thead>
    <tr>
		<th>Menu ID</th>
		<th>Menu</th>
        <th>Menu Category</th>
		<th>QTY</th>
		<th>Total Amount</th>
	</tr>
    </thead>
    <tbody>
        @foreach ($tables as $table)
        <tr>
            <td>{{$table->id}}</td>
            <td>{{$table->name}}</td>
            <td>{{$table->category['name']}}</td>
            <td>{{$table->orderByDate($start_date, $end_date)->sum('quantity')}}</td>
            <td class="right"><span>PHP</span> <span style="margin-left:auto;">{{number_format($table->price * $table->orderByDate($start_date, $end_date)->sum('quantity'))}}</span></td>
        </tr>
        @endforeach
    </tbody>
</table>
@endsection
@section('script')

$(document).ready( function () {
    $('#search').click(function(){
        start = $('#start_date').val();
        end = $('#end_date').val();
        console.log("reports/"+start+"/"+end);
        location.replace("{{route('report')}}/"+start+"/"+end);
    })

    $('table').DataTable();
});
@endsection

resources/views/admin/sales.blade.php
@extends('layouts.app')
@section('style')
td, th{
    text-align:center!important;
    padding:10px;
}
td.right, span.right{
    display:flex;
}
@endsection

@section('content')
<div class="filter">
    <label>DATE</label>
    <input type="date" name="start_date" id="start_date" value="{{$start_date}}">
    <input type="date" name="end_date" id="end_date" value="{{$end_date}}">
    <a><button class="btn btn-primary" id="search">Search</button></a>
    <a href="{{route('sales-export', ['start'=>$start_date,'end'=>$end_date])}}"><button class="btn btn-primary" >Export</button></a>

</div>
<table id="table" class="table table-striped table-bordered">
	<thead>
    <tr>
		<th>Transaction</th>
		<th>Status</th>
        <th>Table</th>
		<th>Total Amount Purchased</th>
		<th>In</th>
		<th>Out</th>
		<th>Transactions</th>
	</tr>
    </thead>
    <tbody>
        @foreach ($tables as $table)

            <tr>
                <td>{{$table->username}}</td>
                <td>{{$table->status}}</td>
                <td>{{$table->table_id}}</td>
                <td class="right"><span>PHP</span> <span style="margin-left:auto;">{{number_format($table->price)}}</span></td>
                <td>{{$table->created_at}}</td>
                <td>{{$table->updated_at}}</td>
                <td>
                    <button class="transaction btn btn-primary" type="button" data-id="{{$table->id}}" data-toggle="modal" data-target="#orderModal">
                        View Transaction
                    </button>
                </td>
            </tr>

        @endforeach
    </tbody>
</table>
<!-- Modal -->
<div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="orderModalLabel">Order: <span id="orderModalUsername"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<table border="1">
            <tr>
                <th width="150px">Menu</th>
                <th>QYT</th>
                <th width="150px">Price</th>
                <th width="200px">Total</th>
            </tr>
            <tbody id="orderModalOrders">

            </tbody>
	      	<tr>
	      		<th colspan="3">Total:</th>
	      		<td id="orderModalPrice" ></td>
	      	</tr>
      	</table>

      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
@endsection
@section('script')

$(document).ready( function () {
    function numberWithCommas(x) {
        return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }

    $('#search').click(function(){
        start = $('#start_date').val();
        end = $('#end_date').val();
        console.log("reports/"+start+"/"+end);
        location.replace("{{route('sales')}}/"+start+"/"+end);
    });
    $('.transaction').click(function() {
        id = $(this).data('id');
        var flickerAPI = "{{route('apicostumers')}}/"+id;
        $('#orderModalOrders').text("");
        $.getJSON( flickerAPI, {
            tags: "mount rainier",
            tagmode: "any",
            format: "json"
        })
        .done(function( data ) {
            $('span#orderModalUsername').text(data.username);
            $('td#orderModalPrice').html("<span class='right'><span>PHP</span> <span style='margin-left:auto;'>"+numberWithCommas(data.price) + "</span></span>");
            $.each( data.order, function( i, item ) {
                if(item.quantity != 0){
                    $( "<tr>" ).appendTo( "#orderModalOrders" );
                    $( "<td>" ).text( item.menu.name ).appendTo( "#orderModalOrders" );
                    $( "<td>" ).text( item.quantity ).appendTo( "#orderModalOrders" );
                    $( "<td>" ).html( "<span class='right'><span>PHP</span> <span style='margin-left:auto;'>" + numberWithCommas(item.menu.price) + "</span></span></td>").appendTo( "#orderModalOrders" );
                    $( "<td>" ).html( "<span class='right'><span>PHP</span> <span style='margin-left:auto;'>" + numberWithCommas(item.menu.price * item.quantity) + "</span></span></td>").appendTo( "#orderModalOrders" );
                    $( "</tr>" ).appendTo( "#orderModalOrders" );
                }
            });
        });
    });
    $('#table').DataTable();

});
@endsection

resources/views/admin/table.blade.php
@extends('layouts.app')

@section('content')

	@include('admin/form-table')

<table  class="table table-striped table-bordered">
	<tr>
		<th>Table</th>
		<th>Status</th>
	</tr>
	@foreach ($tables as $table)
	<tr>
		<td>{{$table->id}}</td>
		<td>{{$table->status}}</td>
	</tr>
	@endforeach
</table>
@endsection

@section('script')

@endsection