routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('costumer/reserve');
});
Route::get('/generate-code', 'GenerateController@display');
//order stage
Route::post('/order', 'TransactionController@stageone');
Route::post('/reorder', 'TransactionController@reorder')->name('reorder');
Route::post('/preparing', 'TransactionController@stagetwo');
Route::post('/request', 'RequestController@store');
Route::get('/done/{id}', 'TransactionController@stagethree')->name('done');
Route::get('/prep/{id}', 'TransactionController@prep')->name('prep');
Route::get('/qrto/{userid}/{pass}/{test}', 'TransactionController@qrRetrive')->name('qr');
Route::get('/testdb', 'TransactionController@test')->name('test');

//admin
Route::post('/status-change', 'AdminController@changeStatus');
Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');
Route::get('/void-order/{id}', 'TransactionController@void')->name('void');
Route::resource('table', 'TableController');
Route::resource('food', 'MenuController');
Route::resource('category', 'CategoryController');
Route::get('reports', 'ReportsController@index')->name('report');
Route::get('reports/{cat}/{date}', 'ReportsController@reportDate')->name('reports');
Route::get('export/{start}/{end}', 'ReportsController@export')->name('export');
Route::get('sale-export/{start}/{end}', 'ReportsController@salesExport')->name('sales-export');
Route::get('sales', 'ReportsController@sales')->name('sales');
Route::get('sales/{start}/{end}', 'ReportsController@salesDate');
Route::post('category/destroy', 'CategoryController@destroy')->name('category.remove');
Route::post('table/destroy', 'TableController@destroy')->name('table.remove');
Route::post('food/destroy', 'MenuController@destroy')->name('food.remove');
Route::post('request/destroy', 'RequestController@destroy')->name('request.remove');
Route::post('food/feat', 'MenuController@feat')->name('food.feat');
Route::post('food/active', 'MenuController@active')->name('food.availability');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Admin') }}</title>
    <link rel="icon" type="image/png" href="{{asset('img/icon.png')}}" />
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <style>
        @yield('style')

    </style>
    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="ap">
    <input type="hidden" name="csrf" id="csrf" value="{{ csrf_token() }}">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ route('home') }}">
                    <img width="80px" src="{{asset('img/icon.png')}}">{{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>

                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('table.index') }}">{{ __('Table') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('food.index') }}">{{ __('Food') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('category.index') }}">{{ __('Category') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('sales') }}">{{ __('Sales') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('report') }}">{{ __('Report') }}</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
        @include('layouts/message')
            <div class="container center">
                <div class="box center">
                    @yield('content')
                </div>
            </div>
        </main>
    </div>
</body>
<script src="{{ mix('js/app.js') }}"></script>
<script>
@yield('script')

</script>
</html>

resources/views/layouts/message.blade.php
<div class="box">
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if($message = Session::get('success'))
	<div class="alert alert-success">
        
            {{ $message }}
        
    </div>
@endif
@if($message = Session::get('error'))
    <div class="alert alert-danger">
        
            {{ $message }}
        
    </div>
@endif
</div>